#ifndef SHADER_CONSTANTS
#define SHADER_CONSTANTS

#define PI 3.1415926

#define INVALID_BONE -1
#define MAX_BONE_NUM 128
#define BONE_NUM_PER_VERTEX 4

#define STD_GAMMA 2.2
#define DIELECTRIC_F0 0.04
#define EPSILON 0.001

#endif